### PR TITLE
implement PSD file format parser

### PR DESCRIPTION
**Pull request by tonyqus**

### CODE REVIEW

**Comment by neilharvey** [comment]
Looks good, thanks for the PR.

**Comment by neilharvey** [comment]
Ack, I just noticed the mime type should be [image/vnd.adobe.photoshop](https://www.iana.org/assignments/media-types/image/vnd.adobe.photoshop) not `image/psd`.  I'll sort it, since I already merged.

**Comment by tonyqus** [comment]
https://github.com/vstinner/hachoir/blob/7ac13e6b63c7ae657fcd0f5eb2c7992a5b7f1cb0/hachoir/parser/image/psd.py#L33

According to [this post](https://wordpress.stackexchange.com/questions/46125/what-is-the-correct-mime-type-for-psd-photoshop), there are a few mimes
```
mage/vnd.adobe.photoshop
application/x-photoshop
application/photoshop
application/psd
image/psd
```

I'm thinking how to support multiple mime types in your library

**Comment by neilharvey** [comment]
IANA has the canonical list of registrations:
https://www.iana.org/assignments/media-types/media-types.xhtml

The only one of those in that list is [image/vnd.adobe.photoshop](https://www.iana.org/assignments/media-types/image/vnd.adobe.photoshop).  The rest are incorrect, it's possible they were used prior to the official registration in 2005.

**Pull request merged**
