### PR TITLE
Adding support for office files with macros

### PR DESCRIPTION
**Pull request by timlarson345**
#71

### CODE REVIEW

**Comment by neilharvey** [comment]
Code looks great, thanks!

It would be good to have some additional test cases for the [FunctionalTests](https://github.com/neilharvey/FileSignatures/blob/master/test/FileSignatures.Tests/FunctionalTests.cs) just to prove that the new code works.  Do you have Excel/Word macro-enabled documents (a blank file is fine) that could be added to the [samples](https://github.com/neilharvey/FileSignatures/tree/master/test/FileSignatures.Tests/Samples)?

**Comment by timlarson345** [comment]
I'll get right on that.

**Comment by timlarson345** [comment]
Tests added.

**Comment by neilharvey** [comment]
Looks good! Thanks for adding the additional tests.  I'll merge in the PR and publish a new release.

**Pull request merged**
